"""Experimental systems landing page.

Lists all experimental features and systems.
"""
from nicegui import ui


@ui.page("/experimental")
def experimental_landing_page():
    """Landing page for experimental systems."""
    
    ui.label("Experimental Systems").classes("text-3xl font-bold mb-4")
    ui.label("These features are experimental and may change or be removed. Use at your own risk.").classes("text-gray-600 mb-6")
    
    # Experimental Systems List
    with ui.card().classes("w-full max-w-4xl p-6"):
        ui.label("Available Experimental Features").classes("text-xl font-semibold mb-4")
        
        # Formula Baseline Charts
        with ui.card().classes("p-4 mb-4 border border-gray-300 bg-gray-50"):
            with ui.row().classes("w-full items-center justify-between"):
                with ui.column().classes("flex-1 gap-2"):
                    with ui.row().classes("items-center gap-2"):
                        ui.label("Formula Baseline Charts").classes("text-lg font-semibold")
                        ui.badge("Usefulness: 0", color="red").classes("text-xs")
                    ui.label(
                        "Theoretical charts for all score and points systems to help refine formulas. "
                        "Includes 6 charts per variable plus correlation charts for weight calibration. "
                        "Each chart has a notes section for analysis."
                    ).classes("text-sm text-gray-700")
                    with ui.card().classes("mt-2 p-2 bg-yellow-50 border border-yellow-200"):
                        ui.label(
                            "Note: Generated by asking to produce many charts without sufficient context or specificity, "
                            "which may relate to the low utility. The actual concept may not be the problem, just the implementation."
                        ).classes("text-xs text-yellow-800 italic")
                ui.button(
                    "Open",
                    on_click=lambda: ui.navigate.to("/experimental/formula-baseline-charts")
                ).classes("bg-blue-500 text-white ml-4")
        
        # Formula Control System
        with ui.card().classes("p-4 mb-4 border border-gray-300"):
            with ui.row().classes("w-full items-center justify-between"):
                with ui.column().classes("flex-1 gap-2"):
                    with ui.row().classes("items-center gap-2"):
                        ui.label("Formula Control System").classes("text-lg font-semibold")
                        ui.badge("Usefulness: 4", color="orange").classes("text-xs")
                    ui.label(
                        "Universal formula control system for adjusting formula parameters dynamically. "
                        "Each formula has its own page with adjustable parameters, real-time Plotly visualizations, "
                        "parameter comparison, and CSV persistence. Settings are automatically synced for immediate use in calculations."
                    ).classes("text-sm text-gray-700")
                ui.button(
                    "Open",
                    on_click=lambda: ui.navigate.to("/experimental/formula-control-system")
                ).classes("bg-blue-500 text-white ml-4")
        
        # Coursera Analysis
        with ui.card().classes("p-4 mb-4 border border-gray-300"):
            with ui.row().classes("w-full items-center justify-between"):
                with ui.column().classes("flex-1 gap-2"):
                    with ui.row().classes("items-center gap-2"):
                        ui.label("Coursera Analysis").classes("text-lg font-semibold")
                        ui.badge("Usefulness: 9", color="green").classes("text-xs")
                    ui.label(
                        "Compare Coursera task completion patterns and productivity metrics. "
                        "Analyze time spent on Coursera and compare productivity scores on days with vs without Coursera. "
                        "Data-driven insights for task prioritization decisions."
                    ).classes("text-sm text-gray-700")
                ui.button(
                    "Open",
                    on_click=lambda: ui.navigate.to("/experimental/coursera-analysis")
                ).classes("bg-blue-500 text-white ml-4")
        
        # Productivity vs Grit Tradeoff
        with ui.card().classes("p-4 mb-4 border border-gray-300"):
            with ui.row().classes("w-full items-center justify-between"):
                with ui.column().classes("flex-1 gap-2"):
                    with ui.row().classes("items-center gap-2"):
                        ui.label("Productivity vs Grit Tradeoff").classes("text-lg font-semibold")
                        ui.badge("Usefulness: 6", color="blue").classes("text-xs")
                    ui.label(
                        "Explore the relationship between productivity (efficiency) and grit (persistence) across all tasks. "
                        "Identify tasks that excel in one metric but not the other. Visualize correlations and quadrant analysis "
                        "to understand the tradeoffs between efficient completion and persistent engagement."
                    ).classes("text-sm text-gray-700")
                ui.button(
                    "Open",
                    on_click=lambda: ui.navigate.to("/experimental/productivity-grit-tradeoff")
                ).classes("bg-blue-500 text-white ml-4")
        
        # Placeholder for future experimental systems
        with ui.card().classes("p-4 bg-gray-50 border border-gray-200"):
            ui.label("More experimental features coming soon...").classes("text-sm text-gray-500 italic")
    
    ui.button("Back to Dashboard", on_click=lambda: ui.navigate.to("/")).classes("mt-4")
